all:
	javac common/IAuthentication.java
	javac common/IBed.java
	javac common/IQualityLevel.java
	javac common/IHotel.java
	javac common/IReservation.java
	javac common/IRegistration.java
	javac common/IRoom.java
	javac common/ISession.java
	javac backend/BedImpl.java
	javac backend/Bill.java
	javac backend/LargerRoom.java
	javac backend/SmallerRoom.java
	javac backend/Room_Impl.java
	javac backend/ReservationImpl.java
	javac backend/Registration_Impl.java
	javac backend/QualityLevelImpl.java
	javac backend/SessionImpl.java
	javac backend/HotelImpl.java
	javac backend/AuthenticationImpl.java
	javac backend/RemoteHotel.java

