all:
	javac frontend/controller/LoginController.java
	javac frontend/controller/RegisterController.java
	javac frontend/controller/Dispatcher.java
	javac frontend/controller/FrontController.java
	javac frontend/controller/ClientController.java
	javac frontend/AdminView.java
	javac frontend/LoginView.java
	javac frontend/RegisterView.java
	javac frontend/EmployeeView.java
	javac frontend/GuestView.java
